spark.master spark://spark-master:7077
spark.driver.memory 1g
spark.executor.memory 1g
spark.executor.cores 1
spark.executor.instances 1
spark.cores.max 1
spark.default.parallelism 1
spark.sql.shuffle.partitions 1
spark.jars.packages io.delta:delta-spark_2.13:4.0.1,org.apache.spark:spark-sql-kafka-0-10_2.13:4.0.2,org.apache.hadoop:hadoop-aws:3.4.1
spark.jars.ivy /opt/spark/ivy
spark.local.dir /tmp/spark-local
spark.storage.cleanupFilesAfterExecutorExit true
spark.sql.extensions io.delta.sql.DeltaSparkSessionExtension
spark.sql.catalog.spark_catalog org.apache.spark.sql.delta.catalog.DeltaCatalog
spark.network.timeout 1000s
spark.executor.heartbeatInterval 100s
spark.hadoop.fs.s3a.endpoint http://minio:9000
spark.hadoop.fs.s3a.access.key minio
spark.hadoop.fs.s3a.secret.key minio123
spark.hadoop.fs.s3a.path.style.access true
spark.hadoop.fs.s3a.connection.ssl.enabled false
spark.hadoop.fs.s3a.impl org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.aws.credentials.provider org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
